# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- master

pool:
  name: Default
  vmImage: Agent

variables:
  tag: '$(Build.BuildId)'

steps:
- template: Gradle.yaml
- template: sonar.yaml
  parameters: 
    cliProjectKey: 'migra2356_Sampleproject_AYLPL14qVoNnHTT-c7K4'
    SonarQube: 'sample-sonar'
- template: container.yaml
- template: test.yaml
- template: artifact.yaml
- template: deploy.yaml